### ISSUE TITLE
Cache bug when broken link is on multiple site pages?

### ISSUE THREAD

**Issue by mdlincoln** [gjtorikian/html-proofer#411] opened 2017-03-22 00:59 UTC
Thank you for an awesome utility! We're gladly using it over at [programminghistorian](http://programminghistorian.org/) to check for dead links in old & new articles.

I believe the cache is not working as advertised in cases where you have the same broken external link on one or more pages of your site. Fixing the link in the original reported location, but not the other, will still result in an error report pointing to a bad link in the original location!

Steps to reproduce:

1. Create two pages with the same erroring link.
2. Run htmlproofer with some `--timespan` so as to create a cache. In the report, it will list only one of the pages with the erroring link.
3. Remove the erroring link from in the page displayed in the htmlproofer report, but leave the bad link in the other, unlisted page.
4. Re-run htmlproofer. The same bad link will be reported as an error, but it will _still be attributed to the page reported from the previous run - the page that you had just fixed_.

As discussed in: https://github.com/programminghistorian/jekyll/issues/390#issuecomment-288156919

**Comment by gjtorikian** [comment] 2017-03-22 03:26
I can't reproduce this scenario exactly, but, I do see some errors in how the cache is handled with multiple failures! I'll look into this ASAP.

**Comment by mdlincoln** [comment] 2017-03-22 15:23
Really? I just tried it with 3.6.0 and got it exactly. Here's a minimal Jekyll site demonstrating the problem: https://github.com/mdlincoln/check_htmlproofer

It has two posts with the same bad link. `check_htmlproofer.sh` will build and check the site, giving a report that `./_site/jekyll/update/2017/03/22/bad-page-2.html` has a bad link. It'll then fix the link, and then rebuild and recheck, resulting in (erroneously) the same error that `bad-page-2` has the broken link, when in fact it's only `bad-page-1` that still has that bad link.

**Comment by fulldecent** [comment] 2017-05-18 15:32
Test case:

```sh
git clone https://github.com/mdlincoln/check_htmlproofer.git
cd check_htmlproofer/
bundle install
./check_htmlproofer.sh 
```

Output

```
---
layout: post
title:  "Site Page 2"
date:   2017-03-22 08:05:13 -0700
categories: jekyll update
---

[Bad Link Here](http://matthewlincoln.net/badlink)
Configuration file: /Users/williamentriken/Desktop/tmp/check_htmlproofer/_config.yml
            Source: /Users/williamentriken/Desktop/tmp/check_htmlproofer
       Destination: /Users/williamentriken/Desktop/tmp/check_htmlproofer/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.273 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
Running ["LinkCheck", "ScriptCheck", "ImageCheck"] on ["./_site"] on *.html... 


/usr/local/lib/ruby/gems/2.4.0/gems/nokogiri-1.6.8.1/lib/nokogiri/html/document.rb:164: warning: constant ::Fixnum is deprecated
Found 0 links in the cache...
Adding 6 links to the cache...
Removing 0 links from the cache...
Checking 6 external links...
Ran on 4 files!


- ./_site/jekyll/update/2017/03/22/bad-page-2.html
  *  External link http://matthewlincoln.net/badlink failed: 404 No error
htmlproofer 3.6.0 | Error:  HTML-Proofer found 1 failure!
---
layout: post
title:  "Site Page 2"
date:   2017-03-22 08:05:13 -0700
categories: jekyll update
---

[Bad Link Fixed!](http://matthewlincoln.net/)
Configuration file: /Users/williamentriken/Desktop/tmp/check_htmlproofer/_config.yml
            Source: /Users/williamentriken/Desktop/tmp/check_htmlproofer
       Destination: /Users/williamentriken/Desktop/tmp/check_htmlproofer/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.233 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
Running ["ImageCheck", "LinkCheck", "ScriptCheck"] on ["./_site"] on *.html... 


/usr/local/lib/ruby/gems/2.4.0/gems/nokogiri-1.6.8.1/lib/nokogiri/html/document.rb:164: warning: constant ::Fixnum is deprecated
Found 6 links in the cache...
Adding 1 link to the cache...
Removing 0 links from the cache...
Checking 2 external links...
Ran on 4 files!


- ./_site/jekyll/update/2017/03/22/bad-page-2.html
  *  External link http://matthewlincoln.net/badlink failed: 404 No error
htmlproofer 3.6.0 | Error:  HTML-Proofer found 1 failure!
```

**Comment by gjtorikian** [comment] 2022-01-02 02:47
@fulldecent thank you so so so much for that small test case.

[The next version of HTMLProofer](https://github.com/gjtorikian/html-proofer/issues/669) has completely rewritten the cache and this is no longer a problem. I am going to close this issue out, as I'm just one person and can't maintain both the 3.x and 4.x features. ✌️ 4.x should release within the month.

**Closed by gjtorikian** 2022-01-02 02:47 UTC
Labels: bug, help wanted
