### ISSUE TITLE
HGroup listed as Invalid Tag

### ISSUE THREAD

**Issue by daniellmb** [gjtorikian/html-proofer#308] opened 2016-02-17 23:00 UTC
example output:

 *  Tag hgroup invalid (line 45)

**Comment by gjtorikian** [comment] 2016-02-18 08:48
This is a duplicate of https://github.com/gjtorikian/html-proofer/issues/298 and will be fixed in the next version of html-proofer :soon:.

**Closed by gjtorikian** 2016-02-18 08:48 UTC
