### ISSUE TITLE
htmlproofer 3.19.2 | Error:  invalid byte sequence in UTF-8 with --timeframe "1w"

### ISSUE THREAD

**Issue by lsolesen** [gjtorikian/html-proofer#662] opened 2021-11-25 21:16 UTC
When I add `--timeframe "1w"` to the command

    bundle exec htmlproofer ./_site --only-4xx --assume-extension --check-favicon --check-html --check_opengraph --http-status-ignore "400, 403, 409, 429" --allow-hash-href --empty_alt_ignore --timeframe "1w"

I get the following error:

```
Running ["LinkCheck", "ImageCheck", "ScriptCheck", "OpenGraphCheck", "HtmlCheck", "FaviconCheck"] on ["./_site"] on *.html... 


htmlproofer 3.19.2 | Error:  invalid byte sequence in UTF-8
Traceback (most recent call last):
        25: from /home/lsolesen/projects/motionsplan-dk-jekyll/vendor/bundle/ruby/2.7.0/bin/htmlproofer:23:in `<main>'
        24: from /home/lsolesen/projects/motionsplan-dk-jekyll/vendor/bundle/ruby/2.7.0/bin/htmlproofer:23:in `load'
        23: from /home/lsolesen/projects/motionsplan-dk-jekyll/vendor/bundle/ruby/2.7.0/gems/html-proofer-3.19.2/bin/htmlproofer:11:in `<top (required)>'
        22: from /home/lsolesen/projects/motionsplan-dk-jekyll/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        21: from /home/lsolesen/projects/motionsplan-dk-jekyll/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        20: from /home/lsolesen/projects/motionsplan-dk-jekyll/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        19: from /home/lsolesen/projects/motionsplan-dk-jekyll/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        18: from /home/lsolesen/projects/motionsplan-dk-jekyll/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        17: from /home/lsolesen/projects/motionsplan-dk-jekyll/vendor/bundle/ruby/2.7.0/gems/html-proofer-3.19.2/bin/htmlproofer:111:in `block (2 levels) in <top (required)>'
        16: from /home/lsolesen/projects/motionsplan-dk-jekyll/vendor/bundle/ruby/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/runner.rb:48:in `run'
        15: from /home/lsolesen/projects/motionsplan-dk-jekyll/vendor/bundle/ruby/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/runner.rb:88:in `check_files'
        14: from /home/lsolesen/projects/motionsplan-dk-jekyll/vendor/bundle/ruby/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/runner.rb:143:in `validate_external_urls'
        13: from /home/lsolesen/projects/motionsplan-dk-jekyll/vendor/bundle/ruby/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/url_validator.rb:29:in `run'
        12: from /home/lsolesen/projects/motionsplan-dk-jekyll/vendor/bundle/ruby/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/cache.rb:134:in `retrieve_urls'
        11: from /home/lsolesen/projects/motionsplan-dk-jekyll/vendor/bundle/ruby/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/cache.rb:88:in `detect_url_changes'
        10: from /home/lsolesen/projects/motionsplan-dk-jekyll/vendor/bundle/ruby/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/cache.rb:88:in `reject'
         9: from /home/lsolesen/projects/motionsplan-dk-jekyll/vendor/bundle/ruby/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/cache.rb:93:in `block in detect_url_changes'
         8: from /home/lsolesen/projects/motionsplan-dk-jekyll/vendor/bundle/ruby/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/log.rb:23:in `log'
         7: from /home/lsolesen/projects/motionsplan-dk-jekyll/vendor/bundle/ruby/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/log.rb:27:in `log_with_color'
         6: from /home/lsolesen/projects/motionsplan-dk-jekyll/vendor/bundle/ruby/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/log.rb:44:in `colorize'
         5: from /home/lsolesen/projects/motionsplan-dk-jekyll/vendor/bundle/ruby/2.7.0/gems/rainbow-3.0.0/lib/rainbow/presenter.rb:108:in `cyan'
         4: from /home/lsolesen/projects/motionsplan-dk-jekyll/vendor/bundle/ruby/2.7.0/gems/rainbow-3.0.0/lib/rainbow/presenter.rb:20:in `color'
         3: from /home/lsolesen/projects/motionsplan-dk-jekyll/vendor/bundle/ruby/2.7.0/gems/rainbow-3.0.0/lib/rainbow/presenter.rb:132:in `wrap_with_sgr'
         2: from /home/lsolesen/projects/motionsplan-dk-jekyll/vendor/bundle/ruby/2.7.0/gems/rainbow-3.0.0/lib/rainbow/string_utils.rb:7:in `wrap_with_sgr'
         1: from /home/lsolesen/projects/motionsplan-dk-jekyll/vendor/bundle/ruby/2.7.0/gems/rainbow-3.0.0/lib/rainbow/string_utils.rb:7:in `match'
/home/lsolesen/projects/motionsplan-dk-jekyll/vendor/bundle/ruby/2.7.0/gems/rainbow-3.0.0/lib/rainbow/string_utils.rb:7:in `match': invalid byte sequence in UTF-8 (ArgumentError)
```

If I run the same without, I have no error. It happens in this repository https://github.com/motionsplan/motionsplan-dk-jekyll/blob/master/.github/workflows/deploy.yml#L66 in my Github Action, but also when I try to run the command with cache locally.

**Comment by riccardoporreca** [comment] 2021-11-25 22:46
@lsolesen, you can better investigate the issue by adding `--log-level debug`

I gave it a quick try, the execution (with `--timeframe`) stops right after:
```
Adding http://www.beastskills.com/tutorials/ to cache check
```
To assess the output more in detail, I redirected the output via `> out`: quite surprisingly, the execution gets past the previous log statements, hinting the issue is with the following statement
```
Adding http://www.beastskills.com/tutorials/ to cache check
Adding http://www.motion-online.dk/fora/index.php?showtopic=29480&hl=kropsv�gt to cache check
[...]
```
There is indeed an encoding issue with `kropsv�gt`.

**Comment by riccardoporreca** [comment] 2021-11-25 23:02
Here a minimal reproducible example (taking the link as written in the source `2009-08-04-traening-med-kropsvaegt.md`):

```bash
echo '<!doctype html>
<html>
<head><title>Example</title></head>
<body>
<a href="http://www.motion-online.dk/fora/index.php?showtopic=29480&hl=kropsv%E6gt">Something wrong here</a>
</body>
</html>' > example.html
htmlproofer ./example.html --external-only --log-level debug --timeframe 1d
# [...]rainbow/string_utils.rb:7:in `match': invalid byte sequence in UTF-8 (ArgumentError)
```
This reproduces the original failure, which seems to happen when trying to log "Adding [...] to the cache". Redirecting the output with `> out`, the execution goes through logging but eventually fails for the same UTF-8 reason while serializing to JSON the cache 
```bash
# [...]html-proofer/cache.rb:126:in `to_json': source sequence is illegal/malformed utf-8 (JSON::GeneratorError)
```

@lsolesen, you probably want to check the link as specified in `2009-08-04-traening-med-kropsvaegt.md`. You can use the example above for a quick test. Note that the right way to specify "æ" in UTF-8 in the URL is `%C3%A6`: Indeed, using `http://www.motion-online.dk/fora/index.php?showtopic=29480&hl=kropsv%C3%A6gt` in the example does the job (assuming `&hl=kropsvægt`) was the intention.

@gjtorikian, there might be the benefit of capturing such issues with non-UTF-8 URLs, to fail with explicit indication of the problematic URL, instead of having uninformative failures as part of logging or cache writing.

**Comment by lsolesen** [comment] 2021-11-26 07:19
Wow. Thanks for a very good explanation. That solved the problem.

tor. 25. nov. 2021 23.46 skrev Riccardo Porreca ***@***.***>:

**Comment by gjtorikian** [comment] 2021-12-31 20:11
Hi—[the next version of HTMLProofer](https://github.com/gjtorikian/html-proofer/issues/669) has been completely rewritten  and this is no longer a problem. I am going to close this issue out, as I'm just one person and can't maintain both the 3.x and 4.x features. ✌️ 4.x should be out within the month.

**Closed by gjtorikian** 2021-12-31 20:11 UTC
