### ISSUE TITLE
allow_missing_href started giving false positives since v4.3

### ISSUE THREAD

**Issue by ianmcburnie** [gjtorikian/html-proofer#800] opened 2023-06-08 21:18 UTC
Our project started getting false positives in our CI build for `allow_missing_href`. Downgrading to v4.2 solved the problem.

**Comment by gjtorikian** [comment] 2023-06-12 13:35
Can you provide more information? Error logs, a reproducible build?

**Comment by gjtorikian** [comment] 2023-07-02 11:53
Closing due to lack of info.

**Closed by gjtorikian** 2023-07-02 11:53 UTC
