### ISSUE TITLE
PDF link with a hash causes PDF-parsing by accident

### ISSUE THREAD

**Issue by scivola** [gjtorikian/html-proofer#663] opened 2021-11-26 01:00 UTC
If we want to make a link to a specified page of a PDF file, we can write as follows:

```html
<a href="foo.pdf#page=2">foo</a>
```

But it causes HTMLProofer to parse of the PDF file as an HTML file.

There are three problems.

[1] This useless parsing wastes CPU time and memory. 

[2] htmlproofer will report a failure as follows:

```
linking to internal hash #page=2 that does not exist
```

[3] Sometimes HTMLProofer raises an ArgumentError such as:

```
/Users/XXXXX/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/html5/document.rb:68:in `parse': Document tree depth limit exceeded (ArgumentError)
```

The exception tends to occur for relatively complicated PDF file.
But I have yet to find the exact conditions for reproducing.

**Comment by stevecheckoway** [comment] 2021-12-06 23:20
The `ArgumentError` is because Nokogiri has a default HTML tree depth of 100 and every sequence of bytes is a valid HTML document. Something about the PDF is causing that limit to be exceeded.

But the main issue is that PDFs shouldn't be parsed by Nokogiri. I tried ignoring PDFs using the `file_ignore` and `url_ignore` options, but neither seemed to be applied.

**Comment by stevecheckoway** [comment] 2021-12-07 02:50
There is a workaround.

```ruby
  HTMLProofer.check_directory(
    "./path",
    { url_ignore: [/.*\.pdf(#.*)?/] }
  ).run
```

**Comment by scivola** [comment] 2021-12-07 07:33
@stevecheckoway 
Thank you for your advice.
But the workaround disables the check for existence of PDFs, too.

**Comment by riccardoporreca** [comment] 2021-12-08 22:21
@scivola, @stevecheckoway, `url_swap` might be your better friend here to check links to PDFs ignoring stripping the hash.

Simple minimal reproducible example:

Bash:

```sh
touch exists.pdf
echo '<!doctype html>
<html>
<head><title>Example</title></head>
<body>
<a href="exists.pdf#page=2">Exists</a>
<a href="missing.pdf#page=2">Missing</a>
</body>
</html>' > example.html
```

Ruby:

```rb
require 'html-proofer'
HTMLProofer.check_file(
    "example.html",
    { :url_swap => {/(?<=\.pdf)#.*$/ => ""} }
).run

#   *  internally linking to missing.pdf#page=2, which does not exist (line 6)
#     <a href="missing.pdf#page=2">Missing</a>
```
Note that the error reports the original full link w/o stripped hash, but the link is in fact checked post-`url_swap`.

**Comment by scivola** [comment] 2021-12-09 00:44
@riccardoporreca 
I could resolve the problem using `url_swap` option. I have adopted `/(?<=\.pdf)#.*/i`.
Thank you for the advice.

**Comment by stevecheckoway** [comment] 2021-12-10 15:24
Thanks @riccardoporreca! Hopefully, html-proofer itself will be fixed, but in the mean time, that's a good workaround.

**Closed** 2021-12-31 20:54 UTC
Labels: next-gen
