### ISSUE TITLE
Invalid element name: code

### ISSUE THREAD

**Issue by msh100** [gjtorikian/html-proofer#280] opened 2015-12-09 11:13 UTC
Since the last release of html proofer, I started getting: `invalid element name`:

```
  *  htmlParseStartTag: invalid element name (line 99)
```

This line in HTML is `</code>`.

**Comment by gjtorikian** [comment] 2015-12-09 22:23
I fat-fingered a typo and provided a release in 2.6.1 (https://github.com/gjtorikian/html-proofer/pull/281). 

I'm going to close this because I'm reasonably sure the problem is the same, but please reopen if 2.6.1 doesn't solve it.

**Closed by gjtorikian** 2015-12-09 22:23 UTC
