### ISSUE TITLE
HTMLproofer does not properly ignore links

### ISSUE THREAD

**Issue by lsolesen** [gjtorikian/html-proofer#756] opened 2022-08-31 07:28 UTC
I am running HTMLProofer 4.4.0 with the following parameters.

```
--only-4xx
--assume-extension
--ignore-status-codes "400,403,409,429"
--allow-hash-href
--ignore-empty-alt
--ignore-urls "bjsm.bmj.com"
--cache '{ "timeframe": { "external": "30d" } }'
```

However I am still getting these errors when running it.

```
* At ./_site/wingate/index.html:284:

  External link https://support.wattbike.com/hc/da/articles/115002920669-The-30-Second-Test failed (status code 403)
```

In previous versions I was using more or less the same parameters, and there it seemed to work. Am I doing something wrong? - or is it because `--only-4xx` is not overridden by `--ignore-status-codes`.

**Comment by gjtorikian** [comment] 2022-09-13 19:26
I'm going to prioritize fixing CLI arg parsing this week. (Although by now people have all probably figured out the workarounds.)

Closing this as a dupe of the above issues.

**Closed by gjtorikian** 2022-09-13 19:26 UTC
