### ISSUE TITLE
CI --ignore-script-embeds not working for me

### ISSUE THREAD

**Issue by publicarray** [gjtorikian/html-proofer#261] opened 2015-11-05 10:50 UTC
I received `Element script embeds close tag (line 129)` with `htmlproof ./_site --check-html --ignore-script-embeds --disable-external --url-ignore "#"` and with
```html
<script data-proofer-ignore>
window.onload = function init() {
    var quiz1 = new dragDropQuiz({
        trailMode: false,
        alertResult: true,
        infoWrong: 'You can catch up on the Solar System <a href="/solar-system.html">here</a>.',
    });
};
</script>
```

**Comment by gjtorikian** [comment] 2015-11-06 00:46
Hmm. Which version of `html-proofer` are you running? I cannot reproduce this. An earlier issue with `htmlproof` was fixed in version 2.4.2.

**Comment by publicarray** [comment] 2015-11-06 00:55
`htmlproof -v`  prints htmlproof 2.5.1

**Comment by publicarray** [comment] 2015-11-06 00:58
![screen shot 2015-11-06 at 10 57 35 am](https://cloud.githubusercontent.com/assets/5497998/10986379/461d8072-8475-11e5-8b78-9260e66fca16.png)

**Comment by publicarray** [comment] 2015-11-06 01:16
I can reproduce in travis builds: https://travis-ci.org/publicarray/solarsystem

steps to reproduce travis build;

1. `git clone https://github.com/publicarray/solarsystem` (54.05 MiB)
2. `cd solarsystem`
3. install bundler if not installed: `gem install bundler`
4. `bundle install`
5. run `./script/cibuild` (runs jekyll build & htmlproof)

**Comment by gjtorikian** [comment] 2015-11-06 17:29
Thanks for those steps! I'm able to reproduce the error. Very frustrating, sorry about that. I'm looking into it.

**Closed** 2015-11-06 21:20 UTC

**Comment by publicarray** [comment] 2015-11-06 23:00
Thank you! this fixed it!
