### ISSUE TITLE
3.18.6 broke before_request

### ISSUE THREAD

**Issue by asbjornu** [gjtorikian/html-proofer#624] opened 2021-02-26 16:00 UTC
Upgrading from 3.18.5 to 3.18.6 somehow broke the `before_request` hook. I'm not sure what, but something in https://github.com/gjtorikian/html-proofer/compare/3bb8d353e0420d79fc97cf06b40081495b871343...75ad787210767ab83aa5c6597662088369b9f105 must change the behaviour such that `before_request` is no longer being invoked, at least in some circumstances. Ideas on what may be the cause would be good so we could both fix it and add more tests to ensure that this doesn't break again.

**Comment by gjtorikian** [comment] 2021-02-27 00:07
Can you provide a minimum reproducible case? https://github.com/gjtorikian/html-proofer/pull/622 probably broke it, but all existing tests passed, so I am curious to know what was missed.

**Comment by asbjornu** [comment] 2021-02-27 00:13
It's not exactly minimal, but [here's where HTMLProofer is in use](https://github.com/SwedbankPay/jekyll-plantuml-docker/blob/b3baed4551f71ec88052e6e9b23308aebd9d495b/.docker/entrypoint/lib/commands/verifier.rb#L39-L41) that broke when upgrading from 3.18.5 to 3.18.6:

**Comment by gjtorikian** [comment] 2021-02-27 16:15
Oh this is the external URL link request, not the middleware one. Hm. 

I guess [this is one of the broken tests](https://github.com/SwedbankPay/jekyll-plantuml-docker/runs/1990840851)? Can you talk me through what you expect to happen and what is happening?  https://github.com/SwedbankPay/jekyll-plantuml-docker/tree/develop/link.md is actually a 404 so I'm not sure what the problem is.

**Comment by asbjornu** [comment] 2021-02-28 00:16
[The failing test](https://github.com/SwedbankPay/jekyll-plantuml-docker/runs/1991597432?check_suite_focus=true#step:6:324) expects a log statement coming from `before_request` that is logged successfully in 3.18.5, but is not logged (and thus failing the spec) in 3.18.6. [The source code for the spec](https://github.com/SwedbankPay/jekyll-plantuml-docker/blob/69ef23bc6ecb67fbefa6285c9d43752c4383b821/.docker/entrypoint/spec/verifier_spec.rb#L98-L105) is:

```ruby
it 'sets bearer token for github' do
    ignore_urls = [ '/', 'http://www.wikipedia.org', %r{[/.]?page1} ]
    allow(context.arguments).to receive(:ignore_urls).and_return(ignore_urls)
    logger = SpecLogger.new(:debug)
    subject.logger = logger
    subject.verify
    expect(logger.message).to include('Authorization set for')
end
```

**Comment by asbjornu** [comment] 2021-02-28 00:17
[The code that performs the logging](https://github.com/SwedbankPay/jekyll-plantuml-docker/blob/b3baed4551f71ec88052e6e9b23308aebd9d495b/.docker/entrypoint/lib/commands/verifier.rb#L46-L57) is:

```ruby
def before_request(request)
  uri = URI(request.base_url)

  unless uri.host.match('github\.(com|io)$')
    log(:debug, "No authorization set for <#{uri}> as it's not matching github.com or github.io.")
    return
  end

  auth = "Bearer #{@context.auth_token}"
  request.options[:headers]['Authorization'] = auth
  log(:debug, "Authorization set for <#{uri}>.")
end
```

**Comment by gjtorikian** [comment] 2021-03-01 22:23
Ok I’ll take a look this week (I’m moving at the moment).

**Comment by gjtorikian** [comment] 2021-03-04 01:55
It looks like this was fixed in your project? I see [3.18.6](https://github.com/SwedbankPay/jekyll-plantuml-docker/blob/768d4462b8dd2754e3144b23266ff684db67835a/tests/full/Gemfile.lock#L31) in your lockfile.

**Comment by asbjornu** [comment] 2021-03-04 01:59
I wish that was true, but that's unfortunately only the lockfile of a test project. [This is the relevant lockfile](https://github.com/SwedbankPay/jekyll-plantuml-docker/blob/768d4462b8dd2754e3144b23266ff684db67835a/.docker/entrypoint/Gemfile.lock#L38) which has locked HTMLProofer to `3.18.5` still.

**Comment by gjtorikian** [comment] 2021-03-04 02:03
I'm a bit stumped. I can't recreate this locally, and nothing dealing with `before_request` was changed. 🤔

**Comment by lizzby** [comment] 2021-03-04 04:25
in a tech dominated world, are you losing your grip on reality?

Sent from Yahoo Mail for iPhone


On Thursday, March 4, 2021, 10:03 AM, Garen Torikian <notifications@github.com> wrote:




I'm a bit stumped. I can't recreate this locally, and nothing dealing with before_request was changed. 🤔

**Comment by gjtorikian** [comment] 2021-03-04 11:55
Ah! I found a culprit. I cloned your project and was able to recreate an issue. One moment...

**Closed** 2021-03-04 12:59 UTC

**Comment by gjtorikian** [comment] 2021-03-04 13:00
Thanks for your patience. 3.18.7 will be released with the fix soon.

PS If this open source project is helping you, please consider sponsoring it. ✌️

**Comment by asbjornu** [comment] 2021-03-05 08:13
Thanks @gjtorikian! The bump from Dependabot came tonight and unfortunately, [it still looks to be broken](https://github.com/SwedbankPay/jekyll-plantuml-docker/pull/150/checks?check_run_id=2036480355#step:6:325). 😕

**Comment by gjtorikian** [comment] 2021-03-05 11:13
😠

**Comment by gjtorikian** [comment] 2021-03-05 11:36
@asbjornu Ok, here's what I think is happening: I think your test might be wrong. Your test relies on the cache, so on the first run, it passes; on the second run, it relies on the response stored in the cache file, and so never actually makes the external request.

To fix this, you can either `rm tmp/.htmlproofer/cache.log` to get it to a clean state; or, use something like Timecop to move outside of the cache timeframe and force html-proofer to ignore what's in the cache. The first option is probably easier. 

Let me know how that goes!

**Comment by asbjornu** [comment] 2021-03-05 12:51
Sorry for being stupid – you are entirely correct. The caching was indeed the problem. [This fixed it](https://github.com/SwedbankPay/jekyll-plantuml-docker/pull/150/commits/9761fc908fe4e41933014b7e8c20a59651bf3925):

```ruby
after { FileUtils.rm_rf(File.expand_path(File.join(__dir__, '..', 'tmp'))) }
```

**Comment by gjtorikian** [comment] 2021-03-05 13:22
No worries at all. There _was_ a legitimate problem with caching around here, which the last patch bump fixed.
