### ISSUE TITLE
Multiple --url-ignore

### ISSUE THREAD

**Issue by ilg-ul** [gjtorikian/html-proofer#377] opened 2017-02-04 15:42 UTC
I noticed that the definition of `--url-ignore` displayed by --help uses a single option and a comma separated list of URLs.

```
bundle exec htmlproofer \
  --url-ignore "https://developer.apple.com/xcode/downloads/,http://developer.apple.com/xcode/downloads/" \
  "${site}"
```

I think it would be useful to also construct the list from multiple options:

```
bundle exec htmlproofer \
  --url-ignore "https://developer.apple.com/xcode/downloads/" \
  --url-ignore "http://developer.apple.com/xcode/downloads/" \
  "${site}"
```

**Comment by gjtorikian** [comment] 2017-02-15 22:55
The problem is that I think the underlying argument parser doesn't support options like that. I believe the parser has the last option "supersede" any of the previous arguments.

If you are aware of a Ruby argument parser that does support both commas as well as multiple `--flag` options, let me know!

**Comment by ilg-ul** [comment] 2017-02-15 22:58
> if you are aware of a Ruby argument parser

Ruby is not really my field of expertise :-(

**Comment by fulldecent** [comment] 2017-05-18 14:30
I have reported this upstream at https://github.com/jekyll/mercenary/issues/49

If this is fixed upstream then we will be able to use the functionality here. Otherwise I do not think we will manually implement that here.

Closing this issue for now we can reopen if that issue is resolved there.

**Closed by fulldecent** 2017-05-18 14:30 UTC
