### ISSUE TITLE
add option to check only unique links

### ISSUE THREAD

**Issue by kenman345** [gjtorikian/html-proofer#473] opened 2018-04-27 14:31 UTC
I help run acceptbitcoincash/acceptbitcoincash and as a directory with some listings in multiple categories, we have a few of the same links on a given page. We check external links with Travis-CI but that takes a lot of time and I have tried to reduce that where I can. 

https://github.com/gjtorikian/html-proofer/blob/0d39b1a8932616c75ba26f8c3bd40ed000977f9b/lib/html-proofer/runner.rb#L58

I have looked over your code and see that you're doing a `.flatten` on the array. I was wondering,  if we could add an option to HTML Proofer `check_external_unique_only` or something along those lines.

The idea is as follows:
After identifying the external links, maybe even before the `swap` happens, to speed things up, you check if this option is enabled. If it is, then you run the array of URLs against the command `.uniq` to remove the duplicates. 

Another thought that comes to mind around this new option is perhaps a way of addressing #411 in which instead of doing `.uniq` you can map the unique urls to the pages they are on. If that link returns as broken, then you can cross-reference your map and output the multiple pages the link is broken on by adding to the errors list per each page so that the structure users define for error ordering can still be maintained properly.

In summation, the availability to make html-proofer run only against unique links and not just every link without any special html tags like `data-proofer-ignore` or having to generate just a single purpose-built list of unique urls, would greatly benefit users and speed up CI build tests as well as hog less bandwidth as we do not spam a site multiple times when they actually do pass the test the first appearance of the URL.

I really hope you consider this capability and let me know if I can help out in any way. I really love using HTML Proofer and hope my idea may be helpful to many.

**Comment by gjtorikian** [comment] 2018-04-29 19:50
Hello! I believe this ought to be the default behavior, and am surprised that it isn’t! That is, there’s no value in making this a configurable option and it should Just Work. I’ll set about fixing that.

By the way, you may also be interested in external link caching, which may also help speed up the tests on Travis: https://github.com/gjtorikian/html-proofer/blob/master/README.md#configuring-caching

**Comment by kenman345** [comment] 2018-04-29 21:00
It does speed things up but I add a new link and it appears on two pages or
the same one twice even then and when the cache expires twice again

**Comment by fulldecent** [comment] 2018-08-06 19:28
I cannot reproduce this bug. Our websites have many duplicate external links.

Would you @kenman345 would you please a test case (GitHub repo + link to Travis CI test case preferred) which demonstrates this behavior?

**Comment by kenman345** [comment] 2018-08-06 19:31
I believe the issue is not that it tests twice but its counting them twice. so it says it sees the same url twice because it appears twice, but I think it only tests once. My thoughts would be that it only displays in the terminal a count of the unique.

**Comment by kenman345** [comment] 2018-08-06 19:32
I will circle back on this, looked over the tests and realized perhaps I am wreong. I will document and report back when I can

**Comment by fulldecent** [comment] 2020-07-02 19:12
Closing for now, please comment back if broken

**Closed by fulldecent** 2020-07-02 19:12 UTC
Labels: test case needed
