### ISSUE TITLE
data-proofer-ignore doesn't ignore HTML validity checks

### ISSUE THREAD

**Issue by ottomatias** [gjtorikian/html-proofer#543] opened 2019-11-11 10:52 UTC
I'm adding social share buttons and the code is not valid HTML. I just learned for example that mailto: links MUST have a recipient in order to be valid, so we have to ignore these links for tests.
However, adding data-proofer-ignore to the elements themselves or their parent doesn't help. 

The code I'm using is this:

```<li><a data-proofer-ignore href="mailto:?subject=&;body=:%20https%3A%2F%2Fwww.domain.com%2F" target="_blank" title="Send email" onclick="window.open('mailto:?subject=' + encodeURIComponent(document.title) + '&body=' +  encodeURIComponent(document.URL)); return false;"><i class="fas fa-envelope-square fa-2x" aria-hidden="true"></i><span class="sr-only">Send email</span></a></li>```

And the proofer spits out:
```  *  187:226: ERROR: htmlParseEntityRef: expecting ';' (line 187)```

This would imply an error just after the ```'&body='```

The code I'm using is from here https://simplesharingbuttons.com.

**Comment by gjtorikian** [comment] 2019-11-11 11:24
Eep, thanks for the example. I'll look into this now.

**Comment by gjtorikian** [comment] 2019-11-11 11:34
I can't reproduce this. Here's [the error](https://travis-ci.org/gjtorikian/html-proofer/jobs/610296252), without the `data-proofer-ignore` (bfe0b7ca7c3da793f223c2bc32ee76dd4b923a7d). And here's [the fix](https://travis-ci.org/gjtorikian/html-proofer/jobs/610296465) showing `data-proofer-ignore` working (1528778801d20c74782352fc611bd22fa452e5b6).

This actually doesn't seem like a link check error, and it's likely that you've passed "check HTML" in (`check_html: true`) as an option, resulting in the error. While that unescaped `&` is in fact an issue, I would expect that `data-proofer-ignore` should ignore that markup as you wished it to.

**Comment by ottomatias** [comment] 2019-11-11 13:34
I noticed I was not running the newest version, but I can reproduce this with 3.13.0. What I didn't say in the beginning is that I'm running htmlproofer on the command line. That shouldn't affect, but..

I made a new html file that contains only 

```<li><a data-proofer-ignore href="mailto:?subject=&;body=:%20https%3A%2F%2Fwww.domain.com%2F" target="_blank" title="Send email" onclick="window.open('mailto:?subject=' + encodeURIComponent(document.title) + '&body=' +  encodeURIComponent(document.URL)); return false;"><i class="fas fa-envelope-square fa-2x" aria-hidden="true"></i><span class="sr-only">Send email</span></a></li>```

And running `htmlproofer --check-html` gives an error. To me `data-proofer-ignore` would mean that all checks should be ignored. Can you reproduce this on command line? I

**Comment by gjtorikian** [comment] 2019-11-11 15:12
> To me `data-proofer-ignore` would mean that all checks should be ignored.

Yes, I agree. I intentionally thought that the issue was that the link was not being ignored, but now I see that it's the HTML check.

**Comment by gjtorikian** [comment] 2021-12-31 17:13
Hi—[the next version of HTMLProofer](https://github.com/gjtorikian/html-proofer/issues/669) won't have HTML checking at all anymore. I am going to close this issue out, as I'm just one person and can't maintain both the 3.x and 4.x features. ✌️

**Closed** 2021-12-31 17:30 UTC
Labels: next-gen
