### ISSUE TITLE
Error:  string contains null byte

### ISSUE THREAD

**Issue by ilyalyo** [gjtorikian/html-proofer#409] opened 2017-03-21 16:06 UTC
Link like:
```html
<a href="https://somelink.com/content.swf#">link</a>
```
with empty bookmark produce 'htmlproofer 3.5.0 | Error:  string contains null byte' error
htmlproofer runs with such options:
```
bundle exec htmlproofer --check-sri --check-external-hash --check-html --check-img-http --check-opengraph --enforce-https --timeframe 6w ./_site/index.html
```
Operating System Details:
Ubuntu 12.04.5 LTS

**Comment by fulldecent** [comment] 2017-05-18 15:26
I cannot reproduce. Here is what I tried:

```sh
mkdir tmp 
cd tmp
echo -e "source \"https://rubygems.org\"\ngem \"html-proofer\"" > Gemfile
bundle install
echo '<a href="index.html#">link</a>' > index.html
bundle exec htmlproofer --check-external-hash --check-html .
```

> Running ["ScriptCheck", "LinkCheck", "ImageCheck", "HtmlCheck"] on ["."] on *.html... 
> 
> 
> Checking 0 external links...
> Ran on 1 file!
> 
> 
> - ./index.html
>   *  linking to index.html#, but  does not exist (line 1)
>      \<a href="index.html#"\>link\</a\>
> htmlproofer 3.6.0 | Error:  HTML-Proofer found 1 failure!

**Comment by ilyalyo** [comment] 2017-05-19 06:26
It produce error with index.html exectly like this:
```html
<a href="https://travel.state.gov/content/dam/passports/FIG_cropper.swf#">
```
I thought its more general, but it works fine for all other links..

**Comment by gjtorikian** [comment] 2017-05-20 16:10
@ilyalyo Do you have the file with that link publicly available somewhere?

`string contains null byte` usually means that there's an encoding problem somewhere. HTML-Proofer expects UTF-8 encoded data, so probably for this one file, something is out of place. It's invisible to the naked eye. If I could get the specific file I could provide more information and probably have Proofer coerce input into UTF-8.

**Comment by ilyalyo** [comment] 2017-05-24 06:48
@gjtorikian file encoding is ascii.
You can download file with this link: https://drive.google.com/open?id=0B3_PHfM1xGNAbml2WGRXc3F6T2s

**Comment by gjtorikian** [comment] 2017-06-01 22:09
Can you convert the file to UTF-8?

**Comment by ilyalyo** [comment] 2017-09-30 18:54
@gjtorikian added PR

**Comment by gjtorikian** [comment] 2017-10-07 21:43
fixed by https://github.com/gjtorikian/html-proofer/pull/454

**Closed by gjtorikian** 2017-10-07 21:43 UTC
Labels: bug
